"""Bounded discovery of review candidates from repository Markdown.

Repository prose is evidence, not authority.  This scanner only locates statements that look
like explicit decisions, rules, conventions, patterns, or constraints and records them as
source-located candidates. The caller decides how to interpret them.

The extraction is deliberately conservative and deterministic.  It reads Markdown bullets in
decision-shaped sections, plus strongly prescriptive statements in the small set of files that
hosts already treat as repository instructions.  It does not ask an LLM to infer intent, and
every result keeps the exact file, line, and nearest heading so a reviewer can judge whether the
text is still current.
"""

import os
import re
from pathlib import Path


_MAX_DOC_FILES = 80
_MAX_FILE_BYTES = 250_000
_MAX_DIRS = 1_000
_MAX_STATEMENTS = 20

_SKIP_DIRS = frozenset({
    ".git", "node_modules", ".venv", "venv", "dist", "build", "target", ".next",
    ".tox", "__pycache__", "site-packages", "vendor",
})
_ALLOWED_DOT_DIRS = frozenset({".claude", ".cursor", ".github", ".windsurf"})
_INSTRUCTION_FILES = frozenset({
    "agents.md", "claude.md", "gemini.md", "contributing.md", "architecture.md",
    "decisions.md", "conventions.md", "constraints.md", "rules.md",
    "copilot-instructions.md",
})
_DECISION_FILE_RE = re.compile(
    r"(?:^|[-_.])(?:adr|architecture|decision|convention|constraint|design|guideline|rule)s?"
    r"(?:[-_.]|$)", re.I)
_HISTORICAL_FILE_RE = re.compile(
    r"(?:^|[-_.])(?:archives?|benchmarks?|campaigns?|changelogs?|drafts?|history|pilots?|"
    r"plans?|progress|proposals?|release-notes?)(?:[-_.]|$)", re.I)
_GENERATED_MARKERS = ("auto-generated", "autogenerated", "@generated", "do not edit")

_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$")
_LIST_RE = re.compile(r"^\s{0,3}(?:[-*+]\s+|\d+[.)]\s+)(.+)$")
_CHECKBOX_RE = re.compile(r"^\[[ xX]\]\s+")
_LINK_RE = re.compile(r"\[([^]]+)]\([^)]+\)")
_MARKUP_RE = re.compile(r"(?:\*\*|__|`)")
_SPACE_RE = re.compile(r"\s+")

_DECISION_HEADING_RE = re.compile(
    r"\b(?:architecture|architectural decisions?|decisions?|rules?|conventions?|constraints?|"
    r"requirements?|invariants?|guidelines?|design principles?|patterns?|important instructions?|"
    r"accepted|rationale)\b", re.I)
_NON_GOVERNING_HEADING_RE = re.compile(
    r"^(?:how|what|when|where|which|who|why|see|understanding)\b", re.I)
_CONSTRAINT_HEADING_RE = re.compile(
    r"\b(?:constraints?|requirements?|invariants?|rules?|important instructions?)\b", re.I)
_CONVENTION_HEADING_RE = re.compile(r"\b(?:conventions?|guidelines?|workflow|style)\b", re.I)
_PATTERN_HEADING_RE = re.compile(r"\bpatterns?\b", re.I)

_PRESCRIPTIVE_RE = re.compile(
    r"\b(?:must(?:n't| not)?|never|always|required|forbidden|do not|don't|cannot|can't|"
    r"should(?:n't| not)?|prefer|avoid)\b", re.I)
_DECISION_TEXT_RE = re.compile(
    r"\b(?:we (?:use|chose|choose|decided|require|prefer|avoid|rejected)|"
    r"the (?:system|service|application|project|repository|repo) (?:uses|must|should)|"
    r"use .+ instead of|chosen over|decision:)\b", re.I)
_IMPERATIVE_RE = re.compile(
    r"^(?:use|keep|run|store|route|document|separate|pin|validate|reject|record|prefer|"
    r"avoid|require|write|read|call|return|raise|load|save|create|update|delete|do not|"
    r"never|always|all|no)\b", re.I)


def _source_priority(root: Path, path: Path) -> tuple[int, str]:
    """Put likely governing documents ahead of explanatory or historical prose."""
    rel = path.relative_to(root)
    lowered = rel.as_posix().lower()
    name = path.name.lower()
    if name in _INSTRUCTION_FILES:
        rank = 0
    elif _DECISION_FILE_RE.search(name):
        rank = 1
    elif len(rel.parts) == 1:
        rank = 2
    else:
        rank = 3
    if _HISTORICAL_FILE_RE.search(lowered):
        rank += 10
    return rank, lowered


def _document_paths(root: Path):
    """Yield a deterministic, bounded and authority-prioritized Markdown set."""
    seen_dirs = 0
    paths: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        seen_dirs += 1
        if seen_dirs > _MAX_DIRS or len(paths) >= _MAX_DOC_FILES:
            break
        dirnames[:] = sorted(
            d for d in dirnames
            if d not in _SKIP_DIRS and (not d.startswith(".") or d in _ALLOWED_DOT_DIRS)
        )
        for name in sorted(filenames):
            if len(paths) >= _MAX_DOC_FILES:
                break
            if not name.lower().endswith(".md"):
                continue
            path = Path(dirpath) / name
            try:
                # A Markdown symlink can point outside the repository. Source discovery is
                # repo-local evidence, so following one would both read out of scope and then
                # mislabel the external bytes with an in-repo path.
                if path.is_symlink() or not path.is_file() or path.stat().st_size > _MAX_FILE_BYTES:
                    continue
            except OSError:
                continue
            paths.append(path)
    yield from sorted(paths, key=lambda path: _source_priority(root, path))


def _clean_statement(raw: str) -> str:
    text = _CHECKBOX_RE.sub("", raw.strip())
    text = _LINK_RE.sub(r"\1", text)
    text = _MARKUP_RE.sub("", text)
    text = _SPACE_RE.sub(" ", text).strip()
    if len(text) > 500:
        cut = text.rfind(". ", 0, 499)
        text = text[:cut + 1] if cut >= 40 else text[:499] + "…"
    return text


def _statement_key(text: object) -> str:
    return re.sub(r"\W+", " ", str(text or "")).strip().lower()


def _subtype(heading: str, statement: str) -> str:
    if _CONSTRAINT_HEADING_RE.search(heading) or _PRESCRIPTIVE_RE.search(statement):
        return "constraint"
    if _CONVENTION_HEADING_RE.search(heading):
        return "convention"
    if _PATTERN_HEADING_RE.search(heading):
        return "pattern"
    return "architecture"


def _is_generated(text: str) -> bool:
    """Recognize a short generator banner without excluding docs about generated code."""
    for raw in text[:1_000].splitlines()[:5]:
        line = raw.strip().lstrip("#<!-*/;").strip()
        if not line or len(line) > 80:
            continue
        if any(marker in line.lower() for marker in _GENERATED_MARKERS):
            return True
    return False


def _decision_section(heading: str) -> bool:
    """Exclude Q&A and promotional headings that merely mention a decision or rule."""
    return (bool(_DECISION_HEADING_RE.search(heading))
            and not _NON_GOVERNING_HEADING_RE.search(heading))


def _statement_text(lines: list[str], index: int, listed: re.Match | None) -> tuple[str, int]:
    """Join one Markdown paragraph or an indented list continuation without crossing blocks."""
    parts = [listed.group(1) if listed else lines[index].strip()]
    last = index
    for offset in range(index + 1, len(lines)):
        raw = lines[offset]
        stripped = raw.strip()
        if (not stripped or _HEADING_RE.match(raw) or _LIST_RE.match(raw)
                or stripped.startswith((">", "```", "~~~", "<!--"))):
            break
        if listed and raw == raw.lstrip():
            break
        parts.append(stripped)
        last = offset
    return " ".join(parts), last


def mine_documented_decisions(repo_path: str, documents: dict[str, str] | None = None) -> list[dict]:
    """Return explicit-looking Markdown statements with source evidence.

    A result means only "this statement exists at this location".  It does not mean the
    statement is current, correct, or applicable. Supplied documents are an already-bounded
    snapshot, including explicitly authorized external files; never follow links in them.
    """
    root = Path(repo_path)
    if not root.is_dir():
        return []
    items: list[dict] = []
    seen: set[str] = set()
    if documents is None:
        documents = {}
        for path in _document_paths(root):
            try:
                documents[path.relative_to(root).as_posix()] = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
    for rel, text in documents.items():
        path = Path(rel)
        # Never round-trip an old Contexer-generated mirror as repository authority.
        if _is_generated(text):
            continue
        instruction_file = path.name.lower() in _INSTRUCTION_FILES
        heading = ""
        in_fence = False
        in_comment = False
        lines = text.splitlines()
        consumed_until = -1
        for index, raw_line in enumerate(lines):
            line_number = index + 1
            if index <= consumed_until:
                continue
            stripped = raw_line.strip()
            if stripped.startswith(("```", "~~~")):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            if in_comment:
                if "-->" in stripped:
                    in_comment = False
                continue
            if "<!--" in stripped:
                if "-->" not in stripped.split("<!--", 1)[1]:
                    in_comment = True
                continue
            # Quoted examples and historical excerpts are not the document speaking in its
            # own voice. They may contain strong "must" language, but reviewing them as a
            # current candidate creates exactly the stale-rule trap this feature avoids.
            if not stripped or stripped.startswith(">"):
                continue
            match = _HEADING_RE.match(raw_line)
            if match:
                heading = _clean_statement(match.group(1))
                continue
            listed = _LIST_RE.match(raw_line)
            candidate, consumed_until = _statement_text(lines, index, listed)
            # One review card must remain one decision. Long architecture inventories and
            # module-responsibility paragraphs often contain incidental words like "only" or
            # "never" but bundle many facts; clipping one would turn a non-atomic paragraph
            # into a misleading partial rule.
            if len(candidate) > 350:
                continue
            cleaned = _clean_statement(candidate)
            relevant_section = _decision_section(heading)
            explicit = bool(_PRESCRIPTIVE_RE.search(cleaned)
                            or _DECISION_TEXT_RE.search(cleaned))
            direct_rule = bool(_IMPERATIVE_RE.search(cleaned))
            # A list item is an atomic decision only when it is written as a direct rule or
            # an explicit choice. This rejects architecture/module inventories whose prose
            # happens to contain "never" halfway through. A free paragraph in a decision-
            # shaped section may state the choice in sentence form. Outside such a section,
            # authoritative instruction files contribute only direct rules.
            listed_decision = bool(listed and relevant_section
                                   and (direct_rule or _DECISION_TEXT_RE.search(cleaned)))
            paragraph_decision = bool(not listed and relevant_section and explicit)
            instruction_rule = bool(instruction_file and direct_rule)
            if not (listed_decision or paragraph_decision or instruction_rule):
                continue
            statement = cleaned
            if len(statement) < 12 or statement.endswith(":"):
                continue
            key = rel + "\n" + heading + "\n" + _statement_key(statement)
            if not key or key in seen:
                continue
            seen.add(key)
            items.append({
                "content": statement,
                "subtype": _subtype(heading, statement),
                "source_file": rel,
                "source_line": line_number,
                "source_heading": heading,
            })
            if len(items) >= _MAX_STATEMENTS:
                return items
    return items
